# Site settings
site: kaeruspoon
title: kaeruspoon
keywords: blog
description: >-
  旅行とバイクとドライブと料理と宇宙が好き。
  Ubie Discoveryのプログラマ。
lang: ja_JP
timezone: Asia/Tokyo
google_analytics:   G-TJV7MJCBL6

# Author settings
author:
  name: 大石 司
  bio: 旅行とバイクとドライブと料理と宇宙が好き。<br>Ubie Discoveryのプログラマ。
  picture: assets/images/profile.jpg
  github: tsukasaoishi
  twitter: tsukasa_oishi
  facebook: tsukasa.oishi
  email: tsukasa.oishi@gmail.com

# URL settings
url: "https://www.kaeruspoon.net"
permalink: pretty

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false
