title: kaeruspoon
email: tsukasa.oishi@gmail.com
description: "I am Tsukasa OISHI(おおいしつかさ/大石司).My current interests are Ruby, Kubernetes and Motorcycle."
baseurl: ""
url: "https://www.kaeruspoon.net"
lang: ja_JP
paginate: 20
minima:
  social_links:
    twitter: tsukasa_oishi
    github: tsukasaoishi
twitter:
  username: tsukasa_oishi
  card: summary
facebook:
  admins: 671652438
social:
  name: Tsukasa OISHI
  links:
    - https://github.com/tsukasaoishi
    - https://twitter.com/tsukasa_oishi

markdown: CommonMarkGhPages
highlighter: rouge
remote_theme: jekyll/minima@3cdd14dff1216f561c68329e0b7420c2dc9b796a
plugins:
  - jekyll-avatar
  - jekyll-coffeescript
  - jekyll-commonmark-ghpages
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
