source "https://rubygems.org"

gem "jekyll"
gem "jekyll-avatar"
gem "jekyll-coffeescript"
gem "jekyll-commonmark-ghpages"
gem "jekyll-default-layout"
gem "jekyll-feed"
gem "jekyll-gist"
gem "jekyll-github-metadata"
gem "jekyll-optional-front-matter"
gem "jekyll-paginate"
gem "jekyll-readme-index"
gem "jekyll-relative-links"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"

gem "terminal-table"
gem "kramdown"
gem "kramdown-parser-gfm"
gem "jemoji"
gem "nokogiri"

gem "minima", github: "jekyll/minima"
gem "github-pages-health-check"
